name: corallian
channels:
  - pytorch
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - blas=1.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - cairo=1.16.0
  - certifi=2025.1.31
  - charset-normalizer=3.3.2
  - cpuonly=2.0
  - eigen=3.4.0
  - expat=2.6.4
  - filelock=3.13.1
  - fontconfig=2.14.1
  - freetype=2.12.1
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - gst-plugins-base=1.22.3
  - gstreamer=1.22.3
  - harfbuzz=10.2.0
  - hdf5=1.14.5
  - icc_rt=2022.1.0
  - icu=73.2
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.5
  - joblib=1.4.2
  - jpeg=9e
  - krb5=1.20.1
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240116.2
  - libclang=14.0.6
  - libclang13=14.0.6
  - libdeflate=1.22
  - libffi=3.4.4
  - libglib=2.78.4
  - libiconv=1.17
  - libjpeg-turbo=2.0.0
  - libogg=1.3.5
  - libpng=1.6.39
  - libpq=17.2
  - libprotobuf=4.25.3
  - libtiff=4.5.1
  - libuv=1.48.0
  - libvorbis=1.3.7
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.13.5
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - networkx=3.4.2
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - opencv=4.10.0
  - openjpeg=2.5.2
  - openssl=3.4.1
  - pandas=2.2.3
  - pcre2=10.42
  - pillow=11.1.0
  - pip=25.0
  - pixman=0.44.2
  - pysocks=1.7.1
  - python=3.12.9
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - pytorch=2.5.1
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.2
  - qt-main=5.15.2
  - requests=2.32.3
  - scikit-learn=1.6.1
  - scipy=1.15.1
  - setuptools=75.8.0
  - six=1.16.0
  - sqlite=3.45.3
  - sympy=1.13.3
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - typing_extensions=4.12.2
  - tzdata=2025a
  - ucrt=10.0.22621.0
  - urllib3=2.3.0
  - vc=14.42
  - vc14_runtime=14.42.34433
  - vs2015_runtime=14.42.34433
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
