name: corallian-env  # Ensure it matches the SLURM script
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12.9
  - numpy=1.26.4
  - pandas=2.2.3
  - scipy=1.15.1
  - scikit-learn=1.6.1
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - pip
  - pip:
      - requests
      - opencv-python
      - matplotlib
      - tqdm
