[preprocessing]
UsePreprocessing = true
UseCachedPreprocessing = true
Dirs = ["D:/ORIGINAL (aka MONITORING)/2024 (COMPLETE)/TRANSECT"]
OutputRoot = "D:/CROPPED-CORALS"
BaseInputDir = "D:/ORIGINAL (aka MONITORING)"
InputRecurse = true

[training]
LoadPretrainedModel = true
PretrainedModelFilepath = "C:/Users/Justin/Desktop/Projects/DLSU/thesis/corallian-full-pipeline/test-model.pt"
DoTraining = false
DoValidation = true
SaveModel = true
ResNetModel = 18                          # valid values: 18, 101
ForceUseCuda = false
IndexFile = "D:/CROPPED-CORALS/index.csv"
ImageDir = "D:/CROPPED-CORALS"

ModelFilepath = "C:/Users/Justin/Desktop/Projects/DLSU/thesis/corallian-full-pipeline/resnet18-aspp.pt"

[training.checkpoint]
UseCheckpoints = true
CheckpointFolder = "C:/Users/Justin/Desktop/Projects/DLSU/thesis/corallian-full-pipeline/checkpoints"
CheckpointsPerEpoch = 10
LoadCheckpoint = false
StartEpoch = 1
StartCheckpoint = 1
ReloadCheckpointOnECCError = true
MaxRetriesOnECCError = "none"   # "none" or any integer are valid values, "none" means retry indefinitely


[training.model]
NumClasses = "auto"            # can be any number or "auto"
NumEpochs = 1
BatchSize = 16
Verbose = false
RandomSeed = 42
ValidationSplit = 0.1          # 10%
LossFunction = "cross-entropy" # currently, only cross-entropy loss is supported
ReadInputAsGrayscale = true
LabelColumn = "annotation"  # "annotation": all coral annotations, "aa_ignore": AA vs not AA


[training.model.aspp]
ASPPEnabled = true
ASPPInChannels = 512
ASPPOutChannels = 256
AtrousRates = [6, 12, 18]

[training.model.optimizer]
OptimizerName = "sgd"     # SGD, Adam, or AdamW
SGDLearningRate = 0.01
SGDWeightDecay = 0.001
SGDMomentum = 0.9
AdamLearningRate = 0.001
AdamWeightDecay = 0
AdamWLearningRate = 0.001
AdamWWeightDecay = 0

[training.model.visual_embedding]
EmbeddingEnabled = true

[testing]
DoTesting = true

[logging]
# to revert to print behavior, use LogFormat = "%(message)s"
LogFormat = "[%(asctime)s] %(levelname)s:%(message)s"
UseLogFile = false
LogFile = "C:/Users/Justin/Desktop/Projects/DLSU/thesis/corallian-full-pipeline/pipeline.log"

[wandb]
runname = "Justin"                               # Set this to your name
entity = "jace_dimalanta-de-la-salle-university" # Set this to your team name
project = "corallian-pipeline"                   # Project name
WANDB_API_KEY = ""                               # Add your API key here
relogin = false                                  # Set this to True if you've logged in before
