[preprocessing]
UsePreprocessing = true
UseCachedPreprocessing = true
Dirs = ["D:/ORIGINAL (aka MONITORING)/2024 (COMPLETE)/TRANSECT"]
OutputRoot = "D:/CROPPED-CORALS"
BaseInputDir = "D:/ORIGINAL (aka MONITORING)"
InputRecurse = true

[training]
DoTraining = true
DoValidation = true
UseCachedModel = false
SaveModel = true
ResNetModel = 18                          # valid values: 18, 101
ForceUseCuda = false
IndexFile = "D:/CROPPED-CORALS/index.csv"
ImageDir = "D:/CROPPED-CORALS"

ModelFilepath = "C:/Users/Justin/Desktop/Projects/DLSU/thesis/corallian-full-pipeline/resnet18-aspp.pt"

[training.model]
NumClasses = "auto"            # can be any number or "auto"
NumEpochs = 20
BatchSize = 16
Verbose = false
RandomSeed = 42
ValidationSplit = 0.1          # 10%
LossFunction = "cross-entropy" # currently, only cross-entropy loss is supported

[training.model.aspp]
ASPPEnabled = true
ASPPInChannels = 512
ASPPOutChannels = 256
AtrousRates = [6, 12, 18]

[training.model.optimizer]
OptimizerName = "sgd"  # currently, only sgd is supported
SGDLearningRate = 0.01
SGDWeightDecay = 0.001
SGDMomentum = 0.9

[training.model.visual_embedding]
EmbeddingEnabled = true

[testing]
DoTesting = true

[logging]
# to revert to print behavior, use LogFormat = "%(message)s"
LogFormat = "[%(asctime)s] %(levelname)s:%(message)s"
UseLogFile = false
LogFile = "C:/Users/Justin/Desktop/Projects/DLSU/thesis/corallian-full-pipeline/pipeline.log"
